### ISSUE TITLE
[构][评]关于issue发文规范

### ISSUE THREAD

**Issue by uolcano** [FriEnds-thefriendswholovethefrontend/BonjourGithub#3]
### :sparkling_heart:初衷

为便于大家对issue内容的阅读节省时间，建议对问题发布的行文进行规范。使用issue而不是用qq等IM的好处就在于大家如果没有同一时间在线，还是可以通过这种留言式的阅读，来了解问题动向。可能刚开始时，会需要时间适应与磨合。但是我相信：**规范总比杂乱要好**。
#### 一.标题

在表提前设置简单的标志，方便问题归类。已想到的有：
1.一级：使用**[构]**或**[建]**或者**[C]**（Construct）表示组织建设相关的讨论问题；**[项]**或**[P]**（Project）表示项目相关内容。表示问题的总体方向。
2.二级：使用**[文]**或**[A]**（Article）表示有助于成员使用的技术相关文章；**[论]**或**[D]**（Discuss）表示有待讨论的问题；**[助]**或**[H]**（help）表示寻求技术等相关帮助。表示文章大致内容，（可选）。
3.三级：使用**[拟]**或**[N]**（Nightly）表示拟稿阶段或问题提出阶段，用于issue尚未完成时的情况，表示还未到讨论阶段；**[征]**或者**[G]**（Gather）表示征集意见/建议阶段；**[评]**或者**[E]**（Evaluate）表示对征集的意见/建议进行投票决定；**[定]**或**[F]**（Finalize）表示发文人定稿编辑阶段，定稿完成后将内容更新到repositories的指定文件夹中。表示撰稿阶段。
4.标题主体，应是总结性内容或者带关键词内容，尽量做到言简意赅。
#### 二.内容

issue内容应当保持良好的结构，便于其他人快速阅读与理解。
大致结构如下：
1.描述问题初衷或者背景
2.建议方案
3.方案说明
4.设置截止时间。个人决定应该把讨论分类设置时间长度。
5.附语或附加说明。（可选）
如果是技术问题，在建议方案之前可以描述自己应尝试或调试过后的bug的结果。但总归来说最好是去[stackoverflow](http://stackoverflow.com/)或[segmentfault](https://segmentfault.com/)上问，毕竟我们人少智慧有限。
#### 三.引用与链接

因为考虑到后面会将讨论的内容进行归档定档，存入repositories，所以最后定档的文章内容最后需要添加原issue的引用链接，方便以后问题汇总与查看。Github的文本编辑使用的Markdown，而且还加强了引用，只要输入问题或者文本的hash值或者#1这样表示的序号就会自动索引到指定的链接。
比如：我发的第一篇issue，就是#1，直接使用即可连接到。文本或者代码链接可以直接用hash值。
这是Github给的示例
#### 四.附加说明

讨论完毕后，我们可以确定一个问题描述的模版，放到repositories里，以后大家发文，就可以照葫芦画瓢，填入需要写的内容就好了。
#### 五.水平分割线

最后给出本文的撰稿人和方案的贡献者。
### :hourglass:截止时间

2016-2-29

---

:pencil:author:@uolcano
:two_men_holding_hands:contributor:

**Comment by UtopiaRebels** [comment]
提个建议——其实前缀标识并不是特别显眼，我看好像有个label的功能可以快速筛选何不好好利用？如果用前缀那前缀最好固定，最好用英语字母单字标识，以免查看的时候混淆。

**Comment by uolcano** [comment]
:paperclip:先标记你的建议。@UtopiaRebels 
确实Github是有labels功能，但是内容单一，在具体项目中应该用的多。正如我上面提到的，可能在标明大家讨论的问题的不同阶段时，似乎只有自己定义标题前缀比较适合。
英文前缀我也考虑到了，但是要怎么用还得大家一致同意，然后统一使用，比较合适；否则，各用各的就没有达到统一标准，降低理解障碍的目的了。
不知道你指的**英语字母单字标识**，是不是我上面用的**[A]表示Article** 这种样式的呢？

**Comment by UtopiaRebels** [comment]
@uolcano 
恩，我在想我们能不能自定义label。。
没错，以后就直接用[C],[A],[D]这种前缀，另外最好只有单一前缀，而且感觉分级不是很好理解？
最后，怎么没人啊啊啊啊啊啊啊啊啊=。=

**Comment by uolcano** [comment]
@UtopiaRebels ，比如我这篇issue想表示是关于organization**建设**的文章并且是处于**征集建议**阶段，如果单一前缀的话，是不是就缺少了一个要个关键表述的内容？
是啊，这是周末了，
@89913388
@lilngforging
@qinsmantou
:loudspeaker:大家都没空么？怎么只有三个人冒泡？都还不会用么？这个不需要怎么难的入门门槛啊，只要会回复就可以了呀。

**Comment by 89913388** [comment]
@uolcano 写得不错

**Comment by UtopiaRebels** [comment]
@uolcano 其实你看你写的【构】我们也很难理解为org建设对吧，有很大歧义，如果只用【征】然后标题写明org建设会不会明晰一些？

**Comment by uolcano** [comment]
[征]org建设--关于issue发文规范
酱紫么？ @UtopiaRebels

**Comment by uolcano** [comment]
@89913388 
唔，你有没有一些想法和倡议？

**Comment by UtopiaRebels** [comment]
呃。。类似？至少一眼看上去知道是征集意见这类的？后面具体内容可以再决定，如果只有**[征]issue发文规范**足够表达意思么？当然你这样写**[征]org建设--关于issue发文规范**我觉得已经非常明晰了~~
@uolcano

**Comment by uolcano** [comment]
@UtopiaRebels 
:pushpin:好，关于标题头这一条先这么定下来：
1、撰稿阶段标识
使用[拟]或[N]（Nightly）表示拟稿阶段或问题提出阶段，用于issue尚未完成时的情况，表示还未到讨论阶段；[征]或者[G]（Gather）表示征集意见/建议阶段；[评]或者[E]（Evaluate）表示对征集的意见/建议进行投票决定；[定]或[F]（Finalize）表示发文人定稿编辑阶段，定稿完成后将内容更新到repositories的指定文件夹中。暂用中文标题头，英文标题头做可能的备用。
2、建设分类
使用**org建设**和**proj建设**，分别表示组织建设和项目建设。
3、求助与发问等
使用Github的issues右侧自带的Labels。求助使用help wanted标签，发文使用question标签，其他标签待定。

第1、2点结合使用的Example：[征]org建设--关于issue发文规范。

另外一个建议，对于具体项目要另建repositories，这个仓库主要做出总体规定。

**Comment by uolcano** [comment]
发现可以自定义labels了，以后直接用labels来标记issue标题了。
参考链接如下：
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/
