### ISSUE TITLE
[构][征]关于repositories使用规范

### ISSUE THREAD

**Issue by uolcano** [FriEnds-thefriendswholovethefrontend/BonjourGithub#4]
### 初衷

考虑到组织的repositories是共用的，我们应该约定一个使用和命名规范，以便其他人使用和查找。
### 建议方案

主要是命名规范
1.目录命名
总目录：以项目、讨论和文章作为区分，建立三个总目录，下设其他目录。
作者/撰写人：方便同步到本地时只对自己撰写的目录下的内容进行修改
内容类型：项目内容以项目名简写命名，讨论内容按issue发文规范，文章以
具体命名：以言简意赅为原则自由命名
举个[:chestnut:](http://www.emoji-cheat-sheet.com/)：project1/author/[C]HowToBuildOurOrg/...
2.文件命名
issue定稿和文件的内容，以issue里发布的内容原标题命名
项目命名看具体项目
### 附加说明

暂时只想到这么多，有什么其他的方案可以帮助大家统一使用repositories呢？
### 截止时间

2016-3-5

---

author:@uolcano
contributor:

**Comment by ABCDXIAOXIAOSASA** [comment]
1 关于 html 部分  
  

      game1/uolcano/game.html
      game1/heeerin/game.html
	  
      game1/lilngforging/game.html	  
      game1/qinsmantou/game.html
	  
      game1/Lancelot/game.html	  
      game1/MON/game.html	
	  
      game1/Tomatosouse/game.html	  
      game1/javascriptmxy/game.html	 
	  
      game1/Venus/game.html	  
      game1/ABCD潇潇洒洒/game.html
	  
	  
	  
	  第一个目录   team 共同开发的 项目 name 
	  
	  第二个目录   
	               team 成员 作者 名
	               team 成员 作者github账号 名 
				   team 成员 作者github邮箱 
	  

      第三个目录   作品稿子
	  
	  
	  
   2 关于 第三方lib 第三方framework 部分
	


   3 关于 CSS 部分 
	
	
	
	
   4 关于 js 部分

**Comment by abcdxiaosa** [comment]
1 关于 html 部分  

game1/uolcano/game.html
game1/heeerin/game.html

game1/lilngforging/game.html  
game1/qinsmantou/game.html

game1/Lancelot/game.html  
game1/MON/game.html 

game1/Tomatosouse/game.html  
game1/javascriptmxy/game.html    

game1/Venus/game.html  
game1/ABCD潇潇洒洒/game.html

第一个目录   team 共同开发的 项目 name 

第二个目录  
team 成员 作者 名
team 成员 作者github账号 名 
team 成员 作者github邮箱 

第三个目录   作品稿子

**Comment by ABCDXIAOXIAOSASA** [comment]
It's very easy to make some words **bold** and other words *italic* with Markdown. You can even [link to Google!](http://google.com)

**Comment by ABCDXIAOXIAOSASA** [comment]
It's very easy to make some words **bold** and other words *italic* with Markdown. You can even [link to Google!](http://baidu.com)

**Comment by ABCDXIAOXIAOSASA** [comment]
It's very easy to make some words **bold** and other words *italic* with Markdown. You can even [link to Baidu!](http://baidu.com)

**Comment by UtopiaRebels** [comment]
@ABCDXIAOXIAOSASA Have fun XD

**Comment by ABCDXIAOXIAOSASA** [comment]
# This is an <h1> tag

**Comment by uolcano** [comment]
@ABCDXIAOXIAOSASA 一个人可以完成的小项目可以这么分，但是需要协同完成的就不能这么分了，必须要在同一个目录下建立分支，完成后合并分支。
