### ISSUE TITLE
注意——关于项目分组的相关说明

### ISSUE THREAD

**Issue by uolcano** [FriEnds-thefriendswholovethefrontend/BonjourGithub#6]
据百度前端的微博消息：

> 本次春季班，我们搭建了一个平台来帮助大家进行实践、交流与分享。同时，我们面向大学生，在这次学习过程中融入了竞赛环节，让大家一边学习，一边竞技！由于竞赛的环节及奖励仅仅针对在校生，所以大家在组队的时候，尽量在校生和在校生一队，非在校生和非在校生一队。非在校生除了竞赛环节以外其他均可正常参加。

**注意** ：由于百度要求每组人数3~5人，有分学生组和非学生组，大家在尚未在本讨论敲定之前先不要登录百度，确定身份。当分组确定后，必须先指定一个队长再邀请其他队员。

> 千万要注意后面注册的人员，先别急着登录百度填写资料

现说明分组情况：
1.学生组
现在已经明确@jiamicu(糖炒栗子)/@UtopiaRebels(孤僻症)选择学生组。@ABCDXIAOXIAOSASA似乎也是学生，尚未在线表明意向。

2.非学生组
已明确@qinsmantou(River)选择非学生组。。

3.皆可
由于可能学生组人数不够，而另一组人数超额，需要有人自愿“服从调配”。目前@uolcano预定非学生组(可以伪装成学生，小音大大都是酱紫操作的)

请大家在这个issue下表态分组意愿。
回复投票格式：**非学生组**  /  **学生组**  /  **皆可**。

意向明确后，考虑到分组人数需要，可能有人需要适当调配，表明[皆可]可以当作分组的“服从调配”人。

---

报名流程：http://ife.baidu.com/static/joinhelp.html
相关信息详述：http://ife.baidu.com/static/2016spring.html
准备工作：http://ife.baidu.com/static/warmup.html#modile.qq.com?qq-pf-to=pcqq.group
# 

author:@uolcano
contributor:@UtopiaRebels

**Comment by xiaotian777** [comment]
我参加非学生组。

**Comment by Tomatosouse** [comment]
我也参加非学生组！

**Comment by fujiang-lilng** [comment]
非学生

**Comment by 89913388** [comment]
我参加非学生组

**Comment by uolcano** [comment]
乃们都去了非学生组，看来我只能装学僧了呀:octocat:
